### ISSUE TITLE
Not updating to v2 with tpm

### ISSUE THREAD

**Issue by nopears** [egel/tmux-gruvbox#45] opened 2024-11-26 11:58 UTC
When I removed and reinstalled the plugin via tpm it was still on v1, so I cloned and checkouted to a release/v2-0-0 branch manually. Is it a bug or it's me bugging

**Comment by egel** [comment] 2024-11-26 23:55
Hey @nopears, no it's not a bug. I also fully get the point/need to use new features ;)
The `main` branch is the current latest version (atm still points to v1). Soon will try to merge release/v2 and then the default installation via tmp will become v2 out of the box. For this moment clone+checkout is the way to get to unreleased stuff. thanks for using my tmux plugin, and apologize for the inconvenience.

> sidenote: For the last several weeks, I have been quite overloaded and have no time to release it. I was still testing things + providing some docs, especially for users that want to migrate from v1 to v2 (there is not much, but to guide with the ideology behind it)

**Comment by nopears** [comment] 2024-11-27 05:23
Oh, I see now. Thanks for developing, you really made my tmux experience feel better.

**Comment by nopears** [comment] 2024-11-27 05:47
Also, I've been using v2 for some time. Works great, no issues found

**Comment by egel** [comment] 2024-11-30 22:32
Thanks, also for testing, especially new, unreleased things. That is amazing! 
Soon, I will release the new version, so I will close this ticket for now. 
In case you need/notice something, feel free to open a new one.

**Closed by egel** 2024-11-30 22:32 UTC
Labels: question, feedback wanted
