### ISSUE TITLE
does not seems to fully work on debian 11 (bullseye)

### ISSUE THREAD

**Issue by msoulier** [egel/tmux-gruvbox#22] opened 2022-02-28 10:38 UTC
I've tried in xterm and gnome-terminal on bullseye but the statusline is not styled with the angle separators as expected. If I login remotely from my archlinux laptop, it works fine, so I think it's some kind of terminal problem. I have an almost identical .Xdefaults on both platforms and gnome-terminal doesn't even use that, so I'm out of ideas for why it's not working properly in bullseye. 

Help appreciated.

**Comment by Monksc** [comment] 2022-03-04 02:32
I have a similar issue with the angle seperators not working while using any desktop evironment / window manager other than kde plasma. I use arch linux, alacritty and awesome wm.  I noticed I can get it to work if I use alcritty + tmux to spawn another alacritty and use tmux. The only time I actually dont get the angle seperators to work is when I dont use kde plasman and spawn alacrity not from tmux within tmux, and then use tmux. I also noticed even if I just use alacrity with not tmux I can echo the angle seperators to the screen but I cant echo the angle seperators to the screen if I also use tmux. I have similar issues with other terminal emulators except UXTerm works just fine. It seems to be an issue with my terminal emulator and how its spawned and tmux and not tmux-gruvbox theme but I dont know for sure.

**Comment by Monksc** [comment] 2022-03-04 04:48
I fixed my issue by running `tmux -u`

**Comment by egel** [comment] 2022-07-04 19:57
Hi @msoulier, from what you describe it seems that you are missing "Powerline glyphs" in your font 😉. In the example from the readme file, I used a [hack font](https://sourcefoundry.org/hack/). If this will solve your problem, awesome, otherwise you can let me know - a screenshot will also help. 
If hack font is not a font you like, try to find any other that supports powerline glyphs.

**Comment by msoulier** [comment] 2022-11-26 13:46
So, Terminus on Gnome-terminal in Debian 11 seems to work fine.

**Comment by egel** [comment] 2024-09-05 21:40
The problem is solved. Closing.

**Closed by egel** 2024-09-05 21:40 UTC
Labels: bug, help wanted
