### ISSUE TITLE
Cannot install via tpm

### ISSUE THREAD

**Issue by s-taylor** [egel/tmux-gruvbox#15] opened 2020-11-01 21:49 UTC
When I install this plugin via tpm the install seems to work, but I then get the error `'~/.tmux/plugins/tpm/tpm' returned 1` when reloading shell and the theme doesn't load.
I am on tmux 3.0a, so it might be a tmux issue but all my other plugins seem to work fine. I could potentially downgrade but just using what `apt-get install` provided.

**Comment by egel** [comment] 2020-11-03 08:52
Thank you @s-taylor for this issue. I've seen this problem with the latest update also with tmux 3.1b. I will try to solve this as soon as I can. Any new PR with potential solution warm welcome 🙂

**Comment by egel** [comment] 2020-11-03 12:25
Coping theme manually works fine, so the problem must be related only to the TPM configuration of the theme.

**Comment by msbrigna** [comment] 2020-11-03 12:43
Maybe the problem is related to #14

**Comment by egel** [comment] 2020-11-03 13:44
Grande @msbrigna! 🙌  I can also confirm that this solved the problem for me (iTerm/macOS 10.15.7).

@s-taylor could you check #14 out, if this solves also the problem on your side? If true I'd love to merge #14 🙂

**Comment by egel** [comment] 2020-11-03 13:49
Additonally, I've noticed that the `print` is also causing the problem with `~/.tmux/plugins/tpm/tpm' returned 1` (iTerm/macOS 10.15.7). 

Changing it, to `echo` solves the problem.

**Comment by vignesh0025** [comment] 2020-11-04 13:15
> Additonally, I've noticed that the `print` is also causing the problem with `~/.tmux/plugins/tpm/tpm' returned 1` (iTerm/macOS 10.15.7).
> 
> Changing it, to `echo` solves the problem.

I had the same issue. Changing 'print' to 'echo' in get_theme() solved the issue.

**Comment by egel** [comment] 2020-11-08 22:27
should be resolved by #14

**Closed by egel** 2020-11-08 22:27 UTC

**Comment by s-taylor** [comment] 2020-11-23 21:37
Can confirm it's now fixed, thanks for your help 👍
